echo many tests require postgres active and running or change the tests  code to use only inmemory storage
cd Sharpino.Sample.Test
dotnet run
cd ..
cd Sharpino.Sample.2.Test
dotnet run
cd ..
cd Sharpino.Sample.3.Test
dotnet run
cd ..
cd Sharpino.Sample.6.Test
dotnet run
cd ..
cd Sharpino.Sample.FormerlySaga.Test
dotnet run
cd ..
cd Sharpino.Sample.8
dotnet run 
cd ..
cd Sharpino.Sample.7/ShoppingCartWithSharpino
dotnet run
cd ..
cd ShoppingCartWithSharpinoBinary
dotnet run
cd ../..
cd Sharpino.Sample.9
dotnet run
cd ..
cd Sharpino.Sample.10
dotnet run
cd ..
cd Sharpino.Sample.14
dotnet run
cd ..
cd Sharpino.Sample.15
dotnet run
cd ..
cd Sharpino.Lib.Test
dotnet run
cd ..

