cd Sharpino.Sample.Test
dotnet run
cd ..
cd Sharpino.Sample.2.Test
dotnet run
cd ..
cd Sharpino.Sample.3.Test
dotnet run
cd ..
cd Sharpino.Sample.6.Test
dotnet run
cd ..
cd Sharpino.Sample.FormerlySaga.Test
dotnet run
cd ..
cd Sharpino.Sample.7/ShoppingCartWithSharpino
dotnet run
cd ..
cd ShoppingCartWithSharpinoBinary
dotnet run
cd ../..
