version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: sharpino
      POSTGRES_USER: sharpino
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    

       